ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb.daws90s.shop
REDIS_HOST: redis.daws90s.shop
MYSQL_HOST: mysql.daws90s.shop 
RABBITMQ_HOST: rabbitmq.daws90s.shop 
CATALOGUE_HOST: catalogue.daws90s.shop
USER_HOST: user.daws90s.shop
CART_HOST: cart.daws90s.shop
SHIPPING_HOST: shipping.daws90s.shop
PAYMENT_HOST: payment.daws90s.shop