[local]
localhost

[mongodb]
mongodb.daws90s.shop

[redis]
redis.daws90s.shop

[mysql]
mysql.daws90s.shop

[rabbitmq]
rabbitmq.daws90s.shop

[catalogue]
catalogue.daws90s.shop

[user]
user.daws90s.shop

[cart]
cart.daws90s.shop

[shipping]
shipping.daws90s.shop

[payment]
payment.daws90s.shop

[frontend]
frontend.daws90s.shop